RemoteAutocomplete component
peterliapin/onlinesales.admin pull request #27
Opened 2023-04-11 12:25 UTC by Exmirai

Added RemoteAutocomplete component. Fixed frontmatter validation. Fixed RestoredDataModal text. Updated swagger model. Fixed console error messages

2023-04-11 18:41 UTC, peterliapin commented
@Exmirai please refactor categories to category.

2023-04-11 18:42 UTC, peterliapin requested changes

2023-04-11 18:42 UTC, peterliapin commented on src/lib/automapper/index.ts
> +  categories: [String],
@Exmirai let's make it category instead of multiple categories.

2023-04-11 18:46 UTC, peterliapin commented
@Exmirai please fix merge conflicts.

2023-04-12 07:13 UTC, gsplakmal reviewed
Shouldn't the component/feature naming follow the existing standard such as app-header, error-boundary, module-wrapper, etc... ? 
So FileDropdown may be renamed as file-dropdown and likewise.

2023-04-12 07:21 UTC, Exmirai commented
There's no global, community accepted naming convention afaik

2023-04-12 10:44 UTC, merged